# Generated by Django 4.1.5 on 2023-01-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('infected', models.BooleanField(default=False)),
                ('inventory', models.ManyToManyField(to='myapp.resource')),
            ],
        ),
    ]
